const titles = [
    "director",
    "signed mortgage",
    "chairman",
    "ceo",
    "board member",
    "executive",
    "president",
    "principal",
    "co-founder",
    "partner",
    "operations",
    "manager",
    "maintenance",
    "chair",
    "chief",
    "governing",
    "property",
    "community",
    "construction",
    "landscape",
    "architect",
    "engineer",
    "senior",
    "operating",
    "development",
    "superintendent",
    "vp",
    "pres",
];

module.exports = titles.join("|");
